routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    HomeController,
    BukuController,
    PenerbitController,
    PengadaanController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::prefix('admin')->name('admin.')->group( function() {

    Route::post('/buku/ajax', [BukuController::class, 'ajax'])->name('buku.ajax');
    Route::resource('buku', BukuController::class);;

    Route::post('/penerbit/ajax', [PenerbitController::class, 'ajax'])->name('penerbit.ajax');
    Route::resource('penerbit', PenerbitController::class);;

});

Route::post('/pengadaan/ajax', [PengadaanController::class, 'ajax'])->name('pengadaan.ajax');
Route::get('/pengadaan', [PengadaanController::class, 'index'])->name('pengadaan.index');

app/Models/Penerbit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Penerbit extends Model
{
    use HasFactory;

    protected $table = "penerbit";
    protected $primaryKey = "id_penerbit";
    public $incrementing = false;

    public $fillable = [
        'id_penerbit',
        'nama',
        'alamat',
        'kota',
        'telepon'
    ];


    public function buku(): HasMany
    {
        return $this->hasMany(Buku::class, 'id_penerbit', 'id_penerbit');
    }
}

app/Http/Controllers/PenerbitController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Yajra\DataTables\Html\Builder;

use App\Models\{
    Buku,
    Penerbit
};

class PenerbitController extends Controller
{
    public function ajax(Request $request)
    {
        $getData = Penerbit::all();

        return DataTables::of($getData)
            ->addColumn('action', function ($model) {
                return '
            <div class="btn-group">
                <a href="' . route('admin.penerbit.show', $model->id_penerbit) . '" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                <a href="' . route('admin.penerbit.edit', $model->id_penerbit) . '" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
            </div>
            ';
            })
            ->rawColumns([
                'action'
            ])
            ->make(true);
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request, Builder $builder)
    {
        $page = [
            'Admin',
            'Penerbit',
            'Data Penerbit',
        ];

        $html = $builder
        ->columns([
            ['data' => "id_penerbit", 'name' => "id_penerbit", 'title' => 'ID'],
            ['data' => "nama", 'name' => "nama", 'title' => 'Nama'],
            ['data' => "alamat", 'name' => "alamat", 'title' => 'Alamat'],
            ['data' => "kota", 'name' => "kota", 'title' => 'Kota'],
            ['data' => "telepon", 'name' => "telepon", 'title' => 'Telepon'],
            ['data' => "action", 'name' => "action", 'title' => 'Action'],
        ])
        ->ajax([
            'url' => route('admin.penerbit.ajax'),
            'headers' => [
                'X-CSRF-TOKEN' => "$('meta[name=\"csrf-token\"]').attr('content')"
            ],
            'type' => 'POST'
        ])->parameters([
            "sScrollX" => '100%',
            'bAutoWidth' => false,
            "order" => [
                [0, 'ASC']
            ],
            'columnDefs' => [
                ['targets' => -1, 'width' => '50px']
            ],
            "serverSide" => true,
            'searchDelay' => 350,
            "lengthMenu" => [10, 25, 50, 100],
            'processing' => true
        ]);

        return view('admin.penerbit.index', [
            'page' => $page,
            'html' => $html,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $page = [
            'Admin',
            'Penerbit',
            'Tambah Data Penerbit',
        ];

        return view('admin.penerbit.create', [
            'page'  => $page
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'id_penerbit' => 'required|unique:penerbit',
            'nama' => 'required',
            'alamat' => 'required',
            'kota' => 'required',
            'telepon' => 'required'
        ]);

        Penerbit::create($validated);

        return redirect(route('admin.penerbit.index'))->with('success', 'Berhasil tambah data penerbit dengan ID: ' . $validated['id_penerbit']);
    }

    /**
     * Display the specified resource.
     */
    public function show(Penerbit $penerbit)
    {
        $page = [
            'Admin',
            'Penerbit',
            'Detail Penerbit: ' . $penerbit->id_penerbit . '',
        ];

        return view('admin.penerbit.show', [
            'page'  => $page,
            'penerbit'  => $penerbit,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Penerbit $penerbit)
    {
        $page = [
            'Admin',
            'Penerbit',
            'Edit Penerbit: ' . $penerbit->id_penerbit . '',
        ];

        return view('admin.penerbit.edit', [
            'page'  => $page,
            'penerbit'  => $penerbit,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Penerbit $penerbit)
    {
        $rules = [
            'nama' => 'required',
            'alamat' => 'required',
            'kota' => 'required',
            'telepon' => 'required'
        ];

        if ($request->input('id_penerbit') != $penerbit->id_penerbit) {
            $rules['id_penerbit'] = 'required|unique:penerbit,id_penerbit';
        }

        $validated = $request->validate($rules);

        $penerbit->update($validated);

        return redirect(route('admin.penerbit.show', $penerbit->id_penerbit))->with('success', 'Berhasil edit data penerbit!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Penerbit $penerbit)
    {
        $penerbit->delete();

        return redirect(route('admin.penerbit.index'))->with('success', 'Berhasil hapus data penerbit!');
    }
}

resources/views/admin/penerbit/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"><a href="{{ route('admin.penerbit.index') }}" class="btn btn-default btn-sm"><i
                            class="fa fa-arrow-left"></i></a> Tambah Data Penerbit</h3>
            </div>
            <form action="{{ route('admin.penerbit.store') }}" method="POST" id="form_add">

                <div class="box-body">

                    @csrf

                    <div class="form-group">
                        <label>ID Penerbit</label>
                        <input type="text" name="id_penerbit" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Nama</label>
                        <input type="text" name="nama" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Alamat</label>
                        <textarea name="alamat" class="form-control" rows="4" required></textarea>
                    </div>

                    <div class="form-group">
                        <label>Kota</label>
                        <input type="text" name="kota" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Telepon</label>
                        <input type="text" name="telepon" class="form-control" required>
                    </div>

                </div>
                <div class="box-footer">
                    <div>
                        <button type="submit" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Tambah Data
                            Penerbit</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

@section('script')
@endsection

resources/views/admin/penerbit/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"><a href="{{ route('admin.penerbit.show', $penerbit->id_penerbit) }}"
                        class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i></a> Edit Data Penerbit
                    {{ $penerbit->id_penerbit }}</h3>
            </div>

            <form action="{{ route('admin.penerbit.update', $penerbit->id_penerbit) }}" method="POST" id="form_edit">
                <div class="box-body">

                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label>ID Penerbit</label>
                        <input type="text" name="id_penerbit" class="form-control" value="{{ $penerbit->id_penerbit }}" required>
                    </div>

                    <div class="form-group">
                        <label>Nama</label>
                        <input type="text" name="nama" class="form-control" value="{{ $penerbit->nama }}" required>
                    </div>

                    <div class="form-group">
                        <label>Nama</label>
                        <textarea name="alamat" class="form-control" rows="4" required>{{ $penerbit->alamat }}</textarea>
                    </div>

                    <div class="form-group">
                        <label>Kota</label>
                        <input type="text" name="kota" class="form-control" value="{{ $penerbit->kota }}" required>
                    </div>

                    <div class="form-group">
                        <label>Telepon</label>
                        <input type="text" name="telepon" class="form-control" value="{{ $penerbit->telepon }}" required>
                    </div>

                </div>
                <div class="box-footer">
                    <div>
                        <button type="button" onclick="confirmDelete()" class="btn btn-danger"><i
                                class="fa fa-trash"></i> Hapus Penerbit</button>
                        <button type="submit" class="btn btn-success pull-right"><i
                                class="fa fa-save"></i> Simpan Data Penerbit</button>
                    </div>
                </div>
            </form>


            <form action="{{ route('admin.penerbit.destroy', $penerbit->id_penerbit) }}" method="POST" id="form_delete">
                @csrf
                @method('DELETE')
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    function confirmDelete(){
        Swal.fire({
            title: `Hapus Data Penerbit?`,
            text: `Semua data yang sudah terpilih akan hilang`,
            icon: "warning",
            showCancelButton: true,
            confirmButtonText: "Ya"
        }).then(function(result) {
            if (result.isConfirmed) {
                $("#form_delete").submit();
            }
        });
    };
</script>
@endsection

resources/views/admin/penerbit/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if($message = Session::get('success'))
            <div class="alert alert-success">
                <h4>{{ $message }}</h4>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Data Penerbit</h3>
                <div class="box-tools pull-right">
                    <a href="{{ route('admin.penerbit.create') }}" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Tambah Penerbit</a>
                </div>
            </div>

            <div class="box-body">
                {!! $html->table(['class' => 'table table-bordered table-hover'], true) !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
{!! $html->scripts() !!}
@endsection

resources/views/admin/penerbit/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if($message = Session::get('success'))
            <div class="alert alert-success">
                <h4>{{ $message }}</h4>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Data Penerbit</h3>
                <div class="box-tools pull-right">
                    <a href="{{ route('admin.penerbit.edit', $penerbit->id_penerbit) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Edit Penerbit</a>
                </div>
            </div>

            <div class="box-body">

                <div class="form-group">
                  <label>ID Penerbit</label>
                  <input type="text" name="id_penerbit" class="form-control" value="{{ $penerbit->id_penerbit }}" disabled>
                </div>

                <div class="form-group">
                    <label>Nama</label>
                    <input type="text" name="nama" class="form-control" value="{{ $penerbit->nama }}" disabled>
                </div>

                <div class="form-group">
                    <label>Alamat</label>
                    <textarea name="alamat" class="form-control" rows="4" disabled>{{ $penerbit->alamat }}</textarea>
                </div>

                <div class="form-group">
                    <label>Kota</label>
                    <input type="text" name="kota" class="form-control" value="{{ $penerbit->kota }}" disabled>
                </div>

                <div class="form-group">
                    <label>Telepon</label>
                    <input type="text" name="telepon" class="form-control" value="{{ $penerbit->telepon }}" disabled>
                </div>


            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
@endsection