routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    HomeController,
    BukuController,
    PenerbitController,
    PengadaanController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::prefix('admin')->name('admin.')->group( function() {

    Route::post('/buku/ajax', [BukuController::class, 'ajax'])->name('buku.ajax');
    Route::resource('buku', BukuController::class);;

    Route::post('/penerbit/ajax', [PenerbitController::class, 'ajax'])->name('penerbit.ajax');
    Route::resource('penerbit', PenerbitController::class);;

});

Route::post('/pengadaan/ajax', [PengadaanController::class, 'ajax'])->name('pengadaan.ajax');
Route::get('/pengadaan', [PengadaanController::class, 'index'])->name('pengadaan.index');

resources/views/layouts/_footer.blade.php
    <script src="{{ asset('bower_components/jquery/dist/jquery.min.js') }}"></script>

    <script src="{{ asset('bower_components/bootstrap/dist/js/bootstrap.min.js') }}"></script>

    <script src="{{ asset('bower_components/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>

    <script src="{{ asset('bower_components/fastclick/lib/fastclick.js') }}"></script>

    <script src="{{ asset('bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>

    <script src="{{ asset('bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js') }}"></script>

    <script src="{{ asset('dist/js/adminlte.min.js') }}"></script>

    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
        })
    </script>

    @yield('script')
</body>

</html>

resources/views/layouts/_header.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>UniBookStore | {{ $page[2] }}</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">

    <link rel="stylesheet" href="{{ asset('bower_components/bootstrap/dist/css/bootstrap.min.css') }}">

    <link rel="stylesheet" href="{{ asset('bower_components/font-awesome/css/font-awesome.min.css') }}">

    <link rel="stylesheet" href="{{ asset('bower_components/Ionicons/css/ionicons.min.css') }}">

    <link rel="stylesheet" href="{{ asset('bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css') }}">

    <link rel="stylesheet" href="{{ asset('dist/css/AdminLTE.min.css') }}">

    <link rel="stylesheet" href="{{ asset('dist/css/skins/_all-skins.min.css') }}">

    <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>

<body class="hold-transition skin-blue sidebar-mini">

resources/views/layouts/_main-header.blade.php
<header class="main-header">

    <a href="/" class="logo">

        <span class="logo-mini"><b>U</b>BS</span>

        <span class="logo-lg"><b>UNI</b>BOOKSTORE</span>
    </a>

    <nav class="navbar navbar-static-top">

        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </a>
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">

                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset('dist/img/user.png') }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">Administrator</span>
                    </a>
                    <ul class="dropdown-menu">

                        <li class="user-header">
                            <img src="{{ asset('dist/img/user.png') }}" class="img-circle" alt="User Image">
                            <p>
                                Administrator
                            </p>
                        </li>

                        <li class="user-footer">
                            <div class="pull-right">
                                <a href="#" class="btn btn-default btn-flat">Sign out</a>
                            </div>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/_sidebar.blade.php
<aside class="main-sidebar">

    <section class="sidebar">

        <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset('dist/img/user.png') }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>Administrator</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div>

        <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i
                            class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form>


        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">MAIN NAVIGATION</li>

            <li class="{{ $page[0] == 'Home' ? 'active' : '' }}">
                <a href="{{ route('home') }}">
                    <i class="fa fa-dashboard"></i> <span>Home</span>
                </a>
            </li>

            <li class="{{ $page[0] == 'Admin' ? 'active menu-open' : '' }} treeview">

                <a href="#">
                    <i class="fa fa-cogs"></i> <span>Admin</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ $page[1] == 'Buku' ? 'active' : '' }}"><a href="{{ route('admin.buku.index') }}"><i class="fa fa-circle-o"></i> Buku</a></li>
                    <li class="{{ $page[1] == 'Penerbit' ? 'active' : '' }}"><a href="{{ route('admin.penerbit.index') }}"><i class="fa fa-circle-o"></i> Penerbit</a></li>
                </ul>

            </li>

            <li class="{{ $page[0] == 'Pengadaan' ? 'active' : '' }}">
                <a href="{{ route('pengadaan.index') }}">
                    <i class="fa fa-th"></i> <span>Pengadaan</span>
                </a>
            </li>

        </ul>
    </section>

</aside>

resources/views/layouts/app.blade.php
@include('layouts._header')

<div class="wrapper">

    @include('layouts._main-header')

    @include('layouts._sidebar')

    <div class="content-wrapper">

        <section class="content-header">
            <h1>
                {{ $page[2] }}
            </h1>
            <ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
                @if ($page[0] == "Admin")
                    <li>{{ $page[1] }}</li>
                @endif
                <li class="active">{{ $page[2] }}</li>
            </ol>
        </section>

        <section class="content">

            @yield('content')

        </section>

    </div>

    <footer class="main-footer">
        <div class="pull-right hidden-xs">
            <b>Version</b> 1.0.0
        </div>
        <strong>Copyright &copy; 2023 <a href="#">UniBookStore</a>.</strong> All rights
        reserved.
    </footer>
</div>

@include('layouts._footer')