routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\{
    HomeController,
    BukuController,
    PenerbitController,
    PengadaanController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::prefix('admin')->name('admin.')->group( function() {

    Route::post('/buku/ajax', [BukuController::class, 'ajax'])->name('buku.ajax');
    Route::resource('buku', BukuController::class);;

    Route::post('/penerbit/ajax', [PenerbitController::class, 'ajax'])->name('penerbit.ajax');
    Route::resource('penerbit', PenerbitController::class);;

});

Route::post('/pengadaan/ajax', [PengadaanController::class, 'ajax'])->name('pengadaan.ajax');
Route::get('/pengadaan', [PengadaanController::class, 'index'])->name('pengadaan.index');

app/Models/Buku.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Buku extends Model
{
    use HasFactory;

    protected $table = "buku";
    protected $primaryKey = "id_buku";
    public $incrementing = false;

    public $fillable = [
        'id_buku',
        'kategori',
        'nama_buku',
        'harga',
        'stok',
        'id_penerbit'
    ];

    public function penerbit(): BelongsTo
    {
        return $this->belongsTo(Penerbit::class, 'id_penerbit', 'id_penerbit');
    }
}

app/Http/Controllers/BukuController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\Datatables\Datatables;
use Yajra\DataTables\Html\Builder;

use App\Models\{
    Buku,
    Penerbit
};

class BukuController extends Controller
{
    public function ajax(Request $request)
    {
        $getData = Buku::with('penerbit')->get();

        return DataTables::of($getData)
        ->addColumn('nama_buku_url', function ($model) {
            return '<a href="' . route('admin.buku.show', $model->id_buku) . '">'. $model->nama_buku .'</a>';
        })
        ->addColumn('nama_penerbit_url', function ($model) {
            return '<a href="' . route('admin.penerbit.show', $model->id_penerbit) . '">'. $model->penerbit->nama .'</a>';
        })
        ->addColumn('action', function ($model){
            return '
            <div class="btn-group">
                <a href="' . route('admin.buku.show', $model->id_buku) . '" class="btn btn-sm btn-default"><i class="fa fa-eye"></i></a>
                <a href="' . route('admin.buku.edit', $model->id_buku) . '" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
            </div>
            ';
        })
        ->rawColumns([
            'action',
            'nama_buku_url',
            'nama_penerbit_url',
        ])
        ->make(true);
    }

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request, Builder $builder)
    {
        $page = [
            'Admin',
            'Buku',
            'Data Buku',
        ];

        $html = $builder
        ->columns([
            ['data' => "id_buku", 'name' => "id_buku", 'title' => 'ID'],
            ['data' => "kategori", 'name' => "kategori", 'title' => 'Kategori'],
            ['data' => "nama_buku", 'name' => "nama_buku", 'title' => 'Nama Buku'],
            ['data' => "harga", 'name' => "harga", 'title' => 'Harga'],
            ['data' => "stok", 'name' => "stok", 'title' => 'Stok'],
            ['data' => "penerbit.nama", 'name' => "penerbit", 'title' => 'Penerbit'],
            ['data' => "action", 'name' => "action", 'title' => 'Action'],
        ])
        ->ajax([
            'url' => route('admin.buku.ajax'),
            'headers' => [
                'X-CSRF-TOKEN' => "$('meta[name=\"csrf-token\"]').attr('content')"
            ],
            'type' => 'POST'
        ])->parameters([
            "sScrollX" => '100%',
            'bAutoWidth' => false,
            "order" => [
                [0, 'ASC']
            ],
            'columnDefs' => [
                ['targets' => -1, 'width' => '50px']
            ],
            "serverSide" => true,
            'searchDelay' => 350,
            "lengthMenu" => [10, 25, 50, 100],
            'processing' => true
        ]);

        return view('admin.buku.index', [
            'page' => $page,
            'html' => $html,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $page = [
            'Admin',
            'Buku',
            'Tambah Data Buku',
        ];

        $getPenerbit = Penerbit::all();

        return view('admin.buku.create', [
            'page'  => $page,
            'getPenerbit'  => $getPenerbit,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'id_buku' => 'required|unique:buku',
            'kategori' => 'required',
            'nama_buku' => 'required',
            'harga' => 'required|integer',
            'stok' => 'required|integer',
            'id_penerbit' => 'required|exists:penerbit,id_penerbit',
        ]);

        Buku::create($validated);

        return redirect(route('admin.buku.index'))->with('success', 'Berhasil tambah data buku dengan ID: ' . $validated['id_buku']);
    }

    /**
     * Display the specified resource.
     */
    public function show(Request $request, Buku $buku)
    {
        $page = [
            'Admin',
            'Buku',
            'Detail Buku: '. $buku->id_buku .'',
        ];

        $getPenerbit = Penerbit::all();

        return view('admin.buku.show', [
            'page'  => $page,
            'buku'  => $buku,
            'getPenerbit'  => $getPenerbit,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Buku $buku)
    {
        $page = [
            'Admin',
            'Buku',
            'Edit Buku: ' . $buku->id_buku . '',
        ];

        $getPenerbit = Penerbit::all();

        return view('admin.buku.edit', [
            'page'  => $page,
            'buku'  => $buku,
            'getPenerbit'  => $getPenerbit,
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Buku $buku)
    {
        $rules = [
            'kategori' => 'required',
            'nama_buku' => 'required',
            'harga' => 'required|integer',
            'stok' => 'required|integer',
            'id_penerbit' => 'required|exists:penerbit,id_penerbit',
        ];

        if ($request->input('id_buku') != $buku->id_buku) {
            $rules['id_buku'] ='required|unique:buku,id_buku';
        }

        $validated = $request->validate($rules);

        $buku->update($validated);

        return redirect(route('admin.buku.show', $buku->id_buku))->with('success', 'Berhasil edit data buku!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Buku $buku)
    {
        $buku->delete();

        return redirect(route('admin.buku.index'))->with('success', 'Berhasil hapus data buku!');
    }
}

resources/views/admin/buku/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"><a href="{{ route('admin.buku.index') }}" class="btn btn-default btn-sm"><i
                            class="fa fa-arrow-left"></i></a> Tambah Data Buku</h3>
            </div>
            <form action="{{ route('admin.buku.store') }}" method="POST" id="form_add">

                <div class="box-body">

                    @csrf

                    <div class="form-group">
                        <label>ID Buku</label>
                        <input type="text" name="id_buku" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Kategori</label>
                        <input type="text" name="kategori" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Nama Buku</label>
                        <input type="text" name="nama_buku" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Harga</label>
                        <input type="number" name="harga" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Stok</label>
                        <input type="number" name="stok" class="form-control" required>
                    </div>

                    <div class="form-group">
                        <label>Penerbit</label>
                        <select name="id_penerbit" class="form-control" required>
                            <option value="">== PILIH PENERBIT ==</option>
                            @foreach ($getPenerbit as $penerbit)
                            <option value="{{ $penerbit->id_penerbit }}">{{ $penerbit->nama }}</option>
                            @endforeach
                        </select>
                    </div>

                </div>
                <div class="box-footer">
                    <div>
                        <button type="submit" class="btn btn-success pull-right"><i class="fa fa-plus"></i> Tambah Data
                            Buku</button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</div>
@endsection

@section('script')
@endsection

resources/views/admin/buku/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title"><a href="{{ route('admin.buku.show', $buku->id_buku) }}"
                        class="btn btn-default btn-sm"><i class="fa fa-arrow-left"></i></a> Edit Data Buku
                    {{ $buku->id_buku }}</h3>
            </div>

            <form action="{{ route('admin.buku.update', $buku->id_buku) }}" method="POST" id="form_edit">
                <div class="box-body">

                    @csrf
                    @method('PUT')

                    <div class="form-group">
                        <label>ID Buku</label>
                        <input type="text" name="id_buku" class="form-control" value="{{ $buku->id_buku }}" required>
                    </div>

                    <div class="form-group">
                        <label>Kategori</label>
                        <input type="text" name="kategori" class="form-control" value="{{ $buku->kategori }}" required>
                    </div>

                    <div class="form-group">
                        <label>Nama Buku</label>
                        <input type="text" name="nama_buku" class="form-control" value="{{ $buku->nama_buku }}"
                            required>
                    </div>

                    <div class="form-group">
                        <label>Harga</label>
                        <input type="number" name="harga" class="form-control" value="{{ $buku->harga }}" required>
                    </div>

                    <div class="form-group">
                        <label>Stok</label>
                        <input type="number" name="stok" class="form-control" value="{{ $buku->stok }}" required>
                    </div>

                    <div class="form-group">
                        <label>Penerbit</label>
                        <select name="id_penerbit" class="form-control" required>
                            @foreach ($getPenerbit as $penerbit)
                            <option value="{{ $penerbit->id_penerbit }}"
                                {{ $buku->penerbit->id_penerbit == $penerbit->id_penerbit ? 'selected' : '' }}>
                                {{ $penerbit->nama }}</option>
                            @endforeach
                        </select>
                    </div>

                </div>
                <div class="box-footer">
                    <div>
                        <button type="button" onclick="confirmDelete()" class="btn btn-danger"><i
                                class="fa fa-trash"></i> Hapus Buku</button>
                        <button type="submit" class="btn btn-success pull-right"><i
                                class="fa fa-save"></i> Simpan Data Buku</button>
                    </div>
                </div>
            </form>


            <form action="{{ route('admin.buku.destroy', $buku->id_buku) }}" method="POST" id="form_delete">
                @csrf
                @method('DELETE')
            </form>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    function confirmDelete(){
        Swal.fire({
            title: `Hapus Data Buku?`,
            text: `Semua data yang sudah terpilih akan hilang`,
            icon: "warning",
            showCancelButton: true,
            confirmButtonText: "Ya"
        }).then(function(result) {
            if (result.isConfirmed) {
                $("#form_delete").submit();
            }
        });
    };
</script>
@endsection

resources/views/admin/buku/index.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if($message = Session::get('success'))
            <div class="alert alert-success">
                <h4>{{ $message }}</h4>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Data Buku</h3>
                <div class="box-tools pull-right">
                    <a href="{{ route('admin.buku.create') }}" class="btn btn-sm btn-primary"><i class="fa fa-plus"></i> Tambah Buku</a>
                </div>
            </div>

            <div class="box-body">
                {!! $html->table(['class' => 'table table-bordered table-hover'], true) !!}
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
{!! $html->scripts() !!}
@endsection

resources/views/admin/buku/show.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
    <div class="col-md-12">

        @if($message = Session::get('success'))
            <div class="alert alert-success">
                <h4>{{ $message }}</h4>
            </div>
        @endif

        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Data Buku</h3>
                <div class="box-tools pull-right">
                    <a href="{{ route('admin.buku.edit', $buku->id_buku) }}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i> Edit Buku</a>
                </div>
            </div>

            <div class="box-body">

                <div class="form-group">
                  <label>ID Buku</label>
                  <input type="text" name="id_buku" class="form-control" value="{{ $buku->id_buku }}" disabled>
                </div>

                <div class="form-group">
                  <label>Kategori</label>
                  <input type="text" name="kategori" class="form-control" value="{{ $buku->kategori }}" disabled>
                </div>

                <div class="form-group">
                  <label>Nama Buku</label>
                  <input type="text" name="nama_buku" class="form-control" value="{{ $buku->nama_buku }}" disabled>
                </div>

                <div class="form-group">
                  <label>Harga</label>
                  <input type="text" name="harga" class="form-control" value="{{ $buku->harga }}" disabled>
                </div>

                <div class="form-group">
                  <label>Stok</label>
                  <input type="text" name="stok" class="form-control" value="{{ $buku->stok }}" disabled>
                </div>

                <div class="form-group">
                  <label>Penerbit</label>
                  <input type="text" name="penerbit" class="form-control" value="{{ $buku->penerbit->nama }}" disabled>
                </div>


            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
@endsection